# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: golang:latest

    working_directory: /go/src/github.com/thedatashed/xlsxreader
    steps:
      - checkout
      - run: go get -v -d ./...
      - run: go test -v -race -cover ./...
      - run: go fmt ./...