# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: golang:latest

    working_directory: ~/repo/
    steps:
      - checkout
      - run:
          name: Test Lint Xlsx Reader
          command: |
            go test -race -cover ./...
            go vet ./...
            test -z $(gofmt -s -l -w .)
